server:
  port: 8881
rpc:
  client:
    load-balance: random
    serialization: PROTOSTUFF
    transport: netty
    registry: zookeeper
    registry-addr: 192.168.48.103:2181
    timeout: 5000

# 设置控制台日志显示级别
logging:
  level:
    com.kitty.rpc: info